### PR TITLE
fix(web): broadcastchannel not supported on old safari 

### LINKED ISSUE #4009: ReferenceError: Can't find variable: BroadcastChannel
### Description

The login page is not loading. It just shows a white screen and there are errors in the console (ReferenceError: Can't find variable: BroadcastChannel). This bug can be observed on some IOS devices - it doesn't matter what browser you use.

### PR DESCRIPTION
**Pull request by james-d-elliott**
This utilizes a wrapper around the BroadcastChannel API to handle browsers which don't properly support the API such as Safari prior to 10.4 and iOS prior to 10.4. Where possible it uses the native API. 

Fixes #4009

### CODE REVIEW

File: web/src/views/LoginPortal/FirstFactor/FirstFactorForm.tsx [hunk 1]
```diff
@@ -52,12 +53,14 @@
...
-        loginChannel.addEventListener("message", (ev) => {
-            if (ev.data) {
+        loginChannel.addEventListener("message", (authenticated) => {
+            if (authenticated) {
                 props.onAuthenticationSuccess(redirectionURL);
             }
         });
+
+
     }, [loginChannel, redirectionURL, props]);
```
Comment (autheliabot) [inline web/src/views/LoginPortal/FirstFactor/FirstFactorForm.tsx:63]: 🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Delete `⏎⏎`
```suggestion
    }, [loginChannel, redirectionURL, props]);
```
