### PR TITLE
fix(handlers): fix redirect with timed out sessions on rules with bypass policy

### LINKED ISSUE #3587: If inactivity timer was exceeded, redirect happens on rules with bypass policy
### Description
If there is a rule for a domain, where only certain resources are protected by a one_factor policy and the rest of the domain (all other resources) are on bypass and you are logged into an Authelia session by some other means, you get redirected to the login page when refreshing a resource, where the bypass policy should be active once your session expired due to inactivity. If you load the URL again, then (without logging in) access is possible again.

### Expected Behaviour
A redirect to the login page should never happen on rules with bypass policy.

### Reproduction Steps
Note: The default policy is deny.

1. Create a rule, where a resource of a domain is protected by a one_factor rule.
2. Create a bypass rule for the domain.
3. Access a resource on the domain that is not covered by the first rule.
4. Log into Authelia by some other means (or by accessing a resource covered by the rule from 1.).
5. Wait until your session expires due to inactivity.
6. Reload the resource from 3. -> You are redirected to the login page.

####
Authelia log
```
time="2022-06-22T17:09:10+02:00" level=error msg="Error caught when verifying user authorization: User alice has been inactive for too long" method=GET path=/api/verify remote_ip=XXX.XXX.XXX.XXX stack="github.com/authelia/authelia/v4/internal/handlers/handler_verify.go:478 VerifyGET.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:53 AutheliaMiddleware.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25 SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35 SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16 SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.9/router.go:414 (*Router).Handler\ngithub.com/valyala/fasthttp@v1.36.0/http.go:153 (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.36.0/server.go:2338 (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.36.0/workerpool.go:224 (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.36.0/workerpool.go:196 (*workerPool).getCh.func1\nruntime/asm_amd64.s:1571 goexit"
time="2022-06-22T17:09:10+02:00" level=info msg="Access to https://app.example.com/_/test (method GET) is not authorized to user alice, responding with status code 302 with location redirect to https://auth.example.com/?rd=https%3A%2F%2Fapp.example.com%2F_%2Ftest&rm=GET" method=GET path=/api/verify remote_ip=XXX.XXX.XXX.XXX
```
Rules:
```yaml
access_control:
    default_policy: deny # Standard
    rules:
    - domain: app.example.com
        resources:
        - '^/internal([/?].*)?$'
        policy: one_factor
    - domain: app.example.com
        policy: bypass
```

### PR DESCRIPTION
**Pull request by mind-ar**
This change replaced a returned error with a warning when the idle timeout was exceeded.

Fixes #3587.

### CODE REVIEW

**Comment by james-d-elliott** [comment]
It's essential for this particular fix that you ensure you write a test that fails without the fix, and doesn't fail after the fix. We also need to ensure there is a test that checks if the rule is not bypass that the redirection occurs but I think that exists.

File: internal/handlers/handler_verify_test.go [hunk 1]
```diff
@@ -1264,3 +1264,37 @@
 	assert.Equal(t, true, refresh)
 	assert.Equal(t, time.Duration(0), interval)
 }
+
+//TestShouldNotRedirectRequestsForByPassedACLWhenInactiveForTooLong
```
Comment (autheliabot) [inline internal/handlers/handler_verify_test.go:1268]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>commentFormatting: put a space between `//` and comment text (gocritic)

File: internal/handlers/handler_verify.go [hunk 2]
```diff
@@ -171,7 +171,10 @@
 				return "", "", nil, nil, authentication.NotAuthenticated, fmt.Errorf("unable to destroy user session after long inactivity: %s", err)
 			}
 
-			return userSession.Username, userSession.DisplayName, userSession.Groups, userSession.Emails, authentication.NotAuthenticated, fmt.Errorf("User %s has been inactive for too long", userSession.Username)
+			ctx.Logger.Warnf("User %s has been inactive for too long", userSession.Username)
+
+			// Fixes #3587
```
Comment (autheliabot) [inline internal/handlers/handler_verify.go:176]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Comment should end in a period (godot)

File: internal/handlers/handler_verify_test.go [hunk 3]
```diff
@@ -1264,3 +1264,37 @@
...
+
+	userSession := mock.Ctx.GetSession()
+	userSession.Username = testUsername
+	userSession.AuthenticationLevel = authentication.TwoFactor
+	userSession.LastActivity = past.Unix()
+
+	err := mock.Ctx.SaveSession(userSession)
+	require.NoError(t, err)
+
+	// should pass
```
Comment (autheliabot) [inline internal/handlers/handler_verify_test.go:1290]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Comment should end in a period (godot)

File: internal/handlers/handler_verify_test.go [hunk 4]
```diff
@@ -1264,3 +1264,37 @@
...
+	mock.Ctx.Request.Header.Set("X-Original-URL", "https://bypass.example.com")
+	VerifyGET(verifyGetCfg)(mock.Ctx)
+	assert.Equal(t, 200, mock.Ctx.Response.StatusCode())
+
+	// should get 401
```
Comment (autheliabot) [inline internal/handlers/handler_verify_test.go:1295]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Comment should end in a period (godot)

File: internal/handlers/handler_verify_test.go [hunk 5]
```diff
@@ -1264,3 +1264,37 @@
...
+	mock.Ctx.Request.Header.Set("X-Original-URL", "https://two-factor.example.com")
+	VerifyGET(verifyGetCfg)(mock.Ctx)
+	assert.Equal(t, 401, mock.Ctx.Response.StatusCode())
+
```
Comment (autheliabot) [inline internal/handlers/handler_verify_test.go:1299]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>unnecessary trailing newline (whitespace)

File: internal/handlers/handler_verify_test.go [hunk 6]
```diff
@@ -1264,3 +1264,37 @@
...
+}
```
Comment (autheliabot) [inline internal/handlers/handler_verify_test.go:1300]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>block should not end with a whitespace (or comment) (wsl)

File: internal/handlers/handler_verify.go [hunk 7]
```diff
@@ -171,7 +171,10 @@ func verifySessionCookie(ctx *middlewares.AutheliaCtx, targetURL *url.URL, userS
 				return "", "", nil, nil, authentication.NotAuthenticated, fmt.Errorf("unable to destroy user session after long inactivity: %s", err)
 			}
 
-			return userSession.Username, userSession.DisplayName, userSession.Groups, userSession.Emails, authentication.NotAuthenticated, fmt.Errorf("User %s has been inactive for too long", userSession.Username)
+			ctx.Logger.Warnf("User %s has been inactive for too long", userSession.Username)
+
+			// Fixes #3587.
+			return userSession.Username, userSession.DisplayName, userSession.Groups, userSession.Emails, authentication.NotAuthenticated, nil
```
Comment (james-d-elliott) [inline internal/handlers/handler_verify.go:177]:
```suggestion
			return "", "", nil, nil, authentication.NotAuthenticated, nil
```

Sorry I was wrong about this. instead change: https://github.com/authelia/authelia/blob/2781a199408fc127088f860ad368bccd7627982c/internal/handlers/handler_verify.go#L266-L269

So that it  doesn't ignore empty usernames (username argument can be removed as part of this change).

File: internal/handlers/handler_verify_test.go [hunk 8]
```diff
@@ -1264,3 +1264,35 @@ func TestGetProfileRefreshSettings(t *testing.T) {
...
+
+	// should pass.
+	mock.Ctx.Request.Header.Set("X-Original-URL", "https://bypass.example.com")
+	VerifyGET(verifyGetCfg)(mock.Ctx)
+	assert.Equal(t, 200, mock.Ctx.Response.StatusCode())
+
+	// should get 401.
+	mock.Ctx.Request.Header.Set("X-Original-URL", "https://two-factor.example.com")
+	VerifyGET(verifyGetCfg)(mock.Ctx)
+	assert.Equal(t, 401, mock.Ctx.Response.StatusCode())
```
Comment (james-d-elliott) [inline internal/handlers/handler_verify_test.go:1297]:
```suggestion
	// Should respond 200 OK.
	mock.Ctx.QueryArgs().Set("rd", "https://login.example.com")
	mock.Ctx.Request.Header.Set("X-Original-URL", "https://bypass.example.com")
	VerifyGET(verifyGetCfg)(mock.Ctx)
	assert.Equal(t, fasthttp.StatusOK, mock.Ctx.Response.StatusCode())
	assert.Nil(t, mock.Ctx.Response.Header.Peek("Location"))

	// Should respond 302 Found.
	mock.Ctx.QueryArgs().Set("rd", "https://login.example.com")
	mock.Ctx.Request.Header.Set("X-Original-URL", "https://two-factor.example.com")
	VerifyGET(verifyGetCfg)(mock.Ctx)
	assert.Equal(t, fasthttp.StatusFound, mock.Ctx.Response.StatusCode())
	assert.Equal(t, "https://login.example.com/?rd=https%3A%2F%2Ftwo-factor.example.com&rm=GET", string(mock.Ctx.Response.Header.Peek("Location")))

	// Should respond 401 Unauthorized.
	mock.Ctx.QueryArgs().Del("rd")
	mock.Ctx.Request.Header.Set("X-Original-URL", "https://two-factor.example.com")
	VerifyGET(verifyGetCfg)(mock.Ctx)
	assert.Equal(t, fasthttp.StatusUnauthorized, mock.Ctx.Response.StatusCode())
	assert.Nil(t, mock.Ctx.Response.Header.Peek("Location"))
```

**Review by james-d-elliott — CHANGES_REQUESTED** [review]

File: internal/handlers/handler_verify_test.go [hunk 9]
```diff
@@ -1264,3 +1264,46 @@
...
+	userSession.LastActivity = past.Unix()
+
+	err := mock.Ctx.SaveSession(userSession)
+	require.NoError(t, err)
+
+	// Should respond 200 OK.
+	mock.Ctx.QueryArgs().Set("rd", "https://login.example.com")
+	mock.Ctx.Request.Header.Set("X-Original-URL", "https://bypass.example.com")
+	VerifyGET(verifyGetCfg)(mock.Ctx)
+	assert.Equal(t, fasthttp.StatusOK, mock.Ctx.Response.StatusCode())
```
Comment (autheliabot) [inline internal/handlers/handler_verify_test.go:1293]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>undeclared name: `fasthttp` (typecheck)

File: internal/handlers/handler_verify_test.go [hunk 10]
```diff
@@ -1264,3 +1264,46 @@
...
+	assert.Nil(t, mock.Ctx.Response.Header.Peek("Location"))
+
+	// Should respond 302 Found.
+	mock.Ctx.QueryArgs().Set("rd", "https://login.example.com")
+	mock.Ctx.Request.Header.Set("X-Original-URL", "https://two-factor.example.com")
+	VerifyGET(verifyGetCfg)(mock.Ctx)
+	assert.Equal(t, fasthttp.StatusFound, mock.Ctx.Response.StatusCode())
```
Comment (autheliabot) [inline internal/handlers/handler_verify_test.go:1300]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>undeclared name: `fasthttp` (typecheck)

File: internal/handlers/handler_verify_test.go [hunk 11]
```diff
@@ -1264,3 +1264,46 @@
...
+	assert.Equal(t, "https://login.example.com/?rd=https%3A%2F%2Ftwo-factor.example.com&rm=GET", string(mock.Ctx.Response.Header.Peek("Location")))
+
+	// Should respond 401 Unauthorized.
+	mock.Ctx.QueryArgs().Del("rd")
+	mock.Ctx.Request.Header.Set("X-Original-URL", "https://two-factor.example.com")
+	VerifyGET(verifyGetCfg)(mock.Ctx)
+	assert.Equal(t, fasthttp.StatusUnauthorized, mock.Ctx.Response.StatusCode())
```
Comment (autheliabot) [inline internal/handlers/handler_verify_test.go:1307]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>undeclared name: `fasthttp` (typecheck)

File: internal/handlers/handler_verify.go [hunk 12]
```diff
@@ -171,8 +171,12 @@
 				return "", "", nil, nil, authentication.NotAuthenticated, fmt.Errorf("unable to destroy user session after long inactivity: %s", err)
 			}
 
-			return userSession.Username, userSession.DisplayName, userSession.Groups, userSession.Emails, authentication.NotAuthenticated, fmt.Errorf("User %s has been inactive for too long", userSession.Username)
+			ctx.Logger.Warnf("User %s has been inactive for too long", userSession.Username)
+
+			// Fixes #3587.
+			return "", "", nil, nil, authentication.NotAuthenticated, nil
+			// return userSession.Username, userSession.DisplayName, userSession.Groups, userSession.Emails, authentication.NotAuthenticated, nil
```
Comment (autheliabot) [inline internal/handlers/handler_verify.go:178]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Comment should end in a period (godot)

**Review by james-d-elliott — APPROVED** [review]
LGTM

File: internal/handlers/handler_verify_test.go [hunk 13]
```diff
@@ -1264,3 +1265,52 @@ func TestGetProfileRefreshSettings(t *testing.T) {
 	assert.Equal(t, true, refresh)
 	assert.Equal(t, time.Duration(0), interval)
 }
+
+func TestShouldNotRedirectRequestsToByPassedACLWhenInactiveForTooLong(t *testing.T) {
```
Comment (nightah) [inline internal/handlers/handler_verify_test.go:1269]:
```suggestion
func TestShouldNotRedirectRequestsForBypassACLWhenInactiveForTooLong(t *testing.T) {
```

**Review by nightah — CHANGES_REQUESTED** [review]
Just a couple of small nits.
