### PR TITLE
fix(notification): incorrect date header format

### LINKED ISSUE #3683: Add 'Message-ID' header to outgoing e-mails
### Description

It would be useful to add a unique `Message-ID` header to e-mails sent by authelia. For example:

> `Message-ID: <1234.foo.5678@authelia.example>`

### Use Case

E-mails without a `Message-ID` header often trigger the spamassassin/rspamd rule `MISSING_MID`.
As a result, authelia's e-mails are delayed or not delivered at all. Here is an example of the bad spam rating:

> X-Rspamd-Bar: +++
> X-Rspamd-Report: MIME_GOOD(-0.1) **MISSING_MID(2.5)** HEADER_DATE_EMPTY_DELIMITER(1) BAYES_HAM(-0.023147)
> X-Rspamd-Score: 3.376852

Delayed e-mails can cause problems with time-sensitive authentication processes. For example, see issue #3569

### PR DESCRIPTION
**Pull request by james-d-elliott**
The date header in the email envelopes was incorrectly formatted missing a space between the `Date:` header and the value of this header. This also refactors the notification templates system allowing people to manually override the envelope itself.

Fixes #3683

ToDo:
- [x] Remove Message-ID from default template. Leave this up to administrators.

### CODE REVIEW

File: internal/authentication/types.go [hunk 1]
```diff
@@ -36,6 +37,23 @@
 	Groups      []string
 }
 
+func (d UserDetails) Addresses() (addresses []mail.Address) {
```
Comment (autheliabot) [inline internal/authentication/types.go:40]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>exported: exported method UserDetails.Addresses should have comment or be unexported (revive)

File: internal/templates/util.go [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+	}
+
+	if info.IsDir() {
+		return false
+	}
+
+	return true
+}
+
+func loadTemplate(name, category, overridePath string) (t *template.Template, err error) {
```
Comment (autheliabot) [inline internal/templates/util.go:23]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`loadTemplate` - `category` always receives `TemplateCategoryNotifications` (`"notification"`) (unparam)

File: internal/templates/provider.go [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+	for i, e := range errs {
+		if i == 0 {
+			err = e
+			continue
+		}
+
+		err = fmt.Errorf("%v, %w", err, e)
+	}
+
+	return fmt.Errorf("one or more errors occcurred loading templates: %w", err)
```
Comment (nightah) [inline internal/templates/provider.go:78]:
```suggestion
	return fmt.Errorf("one or more errors occurred loading templates: %w", err)
```

**Review by nightah — CHANGES_REQUESTED** [review]
Just noticed a small typo.

File: internal/notification/smtp_notifier.go [hunk 4]
```diff
@@ -55,52 +170,56 @@ func (n *SMTPNotifier) startTLS() error {
...
+		)
+
+		if _, ok = n.client.TLSConnectionState(); !ok {
+			return errors.New("client does not support authentication over plain text and the connection is currently plain text")
 		}
 
 		// Check the server supports AUTH, and get the mechanisms.
-		ok, m := n.client.Extension("AUTH")
-		if ok {
+		if ok, m = n.client.Extension("AUTH"); ok {
```
Comment (nightah) [inline internal/notification/smtp_notifier.go:198]:
```suggestion
		if ok, m = n.client.Extension(smtpCommandAUTH); ok {
```

**Review by nightah — APPROVED** [review]
Tiny nit, otherwise LGTM.
