### PR TITLE
fix(storage): postgresql webauthn tbl invalid aaguid constraint

### LINKED ISSUE #5182: Enrolling Yubikey 4 as WebAuthn security key is not possible
### Version

v4.37.5

### Deployment Method

Bare-metal

### Reverse Proxy

NGINX

### Reverse Proxy Version

1.18.0-0ubuntu1.4

### Description

Enrolling a Yubikey 4 as WebAuthn security key results in the following red error message on the portal:

"Failed to register your device. The identity verification process might have timed out."

### Reproduction

Try to enroll a Yubikey 4 (OTP+U2F+CCID) using WebAuthn.

### Expectations

I expected this to just work as Yubikeys can usually be used with other WebAuthn platforms without any issues.

### Configuration (Authelia)

```yaml
---
theme: auto
jwt_secret: "my_jwt_secret"
certificates_directory: "/etc/ssl/certs/"
default_redirection_url: ""
default_2fa_method: totp

server:
  host: 127.0.0.1
  port: 9091
  path: ""

ntp:
  address: "1.2.3.4:123"

authentication_backend:
  password_reset:
    disable: true

  refresh_interval: always
  ldap:
    implementation: custom
    permit_unauthenticated_bind: true
    url: "ldaps://ldap.example.com:636"
    base_dn: "ou=ldap,dc=example,dc=com"
    username_attribute: uid
    users_filter: "(&({username_attribute}={input})(objectClass=posixAccount))"
    groups_filter: (&(memberUid={username})(objectClass=posixGroup))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: gecos

notifier:
  smtp:
    host: mta1.example.com
    port: 25
    identifier: "hostname.example.com"
    sender: "MFA <mfa@example.com>"
    subject: "[MFA] {title}"
    startup_check_address: test@example.com

storage:
  encryption_key: "mykey"
  postgres:
    host: psql.example.com
    port: 5432
    schema: public
    database: "authelia"
    username: "authelia"
    password: "password"

session:
  secret: "secret"
  name: 'auth_session'
  domain: 'example.com'
  same_site: 'lax'
  expiration: '1h'
  inactivity: '5m'
  remember_me_duration: '10h'

webauthn:
  display_name: "MFA"
  attestation_conveyance_preference: direct
  user_verification: preferred

access_control:
  default_policy: deny
  rules:
    - domain: "*.example.com"
      policy: two_factor
...
```

### Logs (Authelia)

```shell
-- Logs begin at Mon 2023-03-20 20:21:47 CET. --
Apr 06 11:00:32 hostname authelia[2677211]: time="2023-04-06T11:00:32+02:00" level=info msg="Shutting down"
Apr 06 11:00:32 hostname systemd[1]: authelia.service: Succeeded.
Apr 06 11:00:32 hostname systemd[1]: Stopped Authelia authentication and authorization server.
Apr 06 11:00:32 hostname systemd[1]: Started Authelia authentication and authorization server.
Apr 06 11:00:32 hostname authelia[2759341]: time="2023-04-06T11:00:32+02:00" level=info msg="Authelia v4.37.5 is starting"
Apr 06 11:00:32 hostname authelia[2759341]: time="2023-04-06T11:00:32+02:00" level=info msg="Log severity set to info"
Apr 06 11:00:44 hostname authelia[2759341]: time="2023-04-06T11:00:44+02:00" level=info msg="Storage schema is being checked for updates"
Apr 06 11:00:44 hostname authelia[2759341]: time="2023-04-06T11:00:44+02:00" level=info msg="Storage schema is already up to date"
Apr 06 11:00:44 hostname authelia[2759341]: time="2023-04-06T11:00:44+02:00" level=info msg="Initializing server for non-TLS connections on '127.0.0.1:9091' path '/'"
Apr 06 11:01:07 hostname authelia[2759341]: time="2023-04-06T11:01:07+02:00" level=error msg="Unable to load Webauthn devices for assertion challenge for user '[redacted uid]': error upserting Webauthn device for user '[redacted uid]' kid '[redacted hex string]': ERROR: null value in column \"aaguid\" violates not-null constraint (SQLSTATE 23502)" method=POST path=/api/secondfactor/webauthn/attestation remote_ip=10.1.2.3 stack="github.com/authelia/authelia/v4/internal/handlers/handler_register_webauthn.go:140 WebauthnAttestationPOST\ngithub.com/authelia/authelia/v4/internal/middlewares/require_first_factor.go:15    Require1FA.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54                  (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25                 SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35                 SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16                 SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.14/router.go:414                                   (*Router).Handler\ngithub.com/valyala/fasthttp@v1.43.0/http.go:154                                    (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2338                                 (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224                              (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196                              (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                                           goexit"
Apr 06 11:02:51 hostname systemd[1]: Stopping Authelia authentication and authorization server...
Apr 06 11:02:51 hostname authelia[2759341]: time="2023-04-06T11:02:51+02:00" level=info msg="Shutting down"
Apr 06 11:02:51 hostname systemd[1]: authelia.service: Succeeded.
Apr 06 11:02:51 hostname systemd[1]: Stopped Authelia authentication and authorization server.
Apr 06 11:02:51 hostname systemd[1]: Started Authelia authentication and authorization server.
Apr 06 11:02:51 hostname authelia[2761722]: time="2023-04-06T11:02:51+02:00" level=info msg="Authelia v4.37.5 is starting"
Apr 06 11:02:51 hostname authelia[2761722]: time="2023-04-06T11:02:51+02:00" level=info msg="Log severity set to info"
Apr 06 11:02:51 hostname authelia[2761722]: time="2023-04-06T11:02:51+02:00" level=info msg="Storage schema is being checked for updates"
Apr 06 11:02:51 hostname authelia[2761722]: time="2023-04-06T11:02:51+02:00" level=info msg="Storage schema is already up to date"
Apr 06 11:02:51 hostname authelia[2761722]: time="2023-04-06T11:02:51+02:00" level=info msg="Initializing server for non-TLS connections on '127.0.0.1:9091' path '/'"
Apr 06 11:03:35 hostname authelia[2761722]: time="2023-04-06T11:03:35+02:00" level=error msg="Unable to load Webauthn devices for assertion challenge for user '[redacted uid]': error upserting Webauthn device for user '[redacted uid]' kid '[redacted hex string]': ERROR: null value in column \"aaguid\" violates not-null constraint (SQLSTATE 23502)" method=POST path=/api/secondfactor/webauthn/attestation remote_ip=10.1.2.3 stack="github.com/authelia/authelia/v4/internal/handlers/handler_register_webauthn.go:140 WebauthnAttestationPOST\ngithub.com/authelia/authelia/v4/internal/middlewares/require_first_factor.go:15    Require1FA.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54                  (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25                 SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35                 SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16                 SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.14/router.go:414                                   (*Router).Handler\ngithub.com/valyala/fasthttp@v1.43.0/http.go:154                                    (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2338                                 (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224                              (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196                              (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                                           goexit"
```

### Logs (Proxy / Application)

_No response_

### Documentation

_No response_

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation

### PR DESCRIPTION
**Pull request by james-d-elliott**
This fixes an issue with the PostgreSQL schema where the webauthn tables aaguid column had a NOT NULL constraint erroneously.

Fixes #5182

### CODE REVIEW

File: internal/model/schema_migration.go [hunk 1]
```diff
@@ -9,6 +13,15 @@
 	Query    string
 }
 
+// NotEmpty returns true if the SchemaMigration is not an empty string.
+func (m SchemaMigration) NotEmpty() bool {
+	if len(strings.TrimSpace(m.Query)) == 0 {
```
Comment (autheliabot) [inline internal/model/schema_migration.go:18]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>S1008: should use 'return len(strings.TrimSpace(m.Query)) != 0' instead of 'if len(strings.TrimSpace(m.Query)) == 0 { return false }; return true' (gosimple)

**Review by nightah — APPROVED** [review]
LGTM.
