### PR TITLE
[SECURITY] Fix Authentication HTTP Status Codes

### LINKED ISSUE #478: Make first factor failures non-success status codes for easy log filtering
Hey @clems4ever,
I have noticed another inconvenience. :sweat_smile: 

Failures in authelia's first factor authentication currently return a 200 status code.
Which is imo not good practice, as the login call was really not 'successful', and very inconvenient for logging authentication failures.

I have traefik configured to log client errors (status codes 400-499), which works nicely for Basic Auth, but fails to detect any failures using authelia's web interface.

I am feeding my logs into fail2ban. I know, that authelia's has its own banning feature, but I am using fail2ban for multiple services on my system (including other traefik services) and would like to reuse it for authelia as well.

From what I have seen browsing the source code, you are using axios on the frontend side, which [should still work fine with 400 codes](https://github.com/clems4ever/authelia/blob/master/web/src/services/Client.ts#L7) and take the same branch.

On the backend side, it seems that [Error](https://github.com/clems4ever/authelia/blob/master/internal/middlewares/authelia_context.go#L49) and [ReplyError](https://github.com/clems4ever/authelia/blob/master/internal/middlewares/authelia_context.go#L62) would need to be adjusted to return different status codes.

Do you think this approach would work, or might that break other parts of authelia? I am not to familiar with go, but I guess I could make a quick PR, if that is all this takes? (And you are agreeing with this request of course.)

(Note: The same might apply to the second factor, but I have not tested that *yet*)

### PR DESCRIPTION
**Pull request by james-d-elliott**
Will close #478 when merged. Adds additional mitigation options against #949

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

### CODE REVIEW

File: internal/handlers/handler_sign_duo.go [hunk 1]
```diff
@@ -60,15 +60,16 @@ func SecondFactorDuoPost(duoAPI duo.API) middlewares.RequestHandler {
 		err = ctx.Providers.SessionProvider.RegenerateSession(ctx.RequestCtx)
 
 		if err != nil {
-			ctx.Error(fmt.Errorf("Unable to regenerate session for user %s: %s", userSession.Username, err), authenticationFailedMessage)
+			// TODO: Shouldn't this be mfaValidationFailedMessage like the rest?
```
Comment (clems4ever) [inline internal/handlers/handler_sign_duo.go:63]: yes you're right.

File: internal/handlers/handler_sign_totp.go [hunk 2]
```diff
@@ -14,40 +14,41 @@ func SecondFactorTOTPPost(totpVerifier TOTPVerifier) middlewares.RequestHandler
...
-			ctx.Error(fmt.Errorf("Wrong passcode during TOTP validation for user %s", userSession.Username), mfaValidationFailedMessage)
+			handleErrorResponse(ctx, fmt.Errorf("Wrong passcode during TOTP validation for user %s", userSession.Username), mfaValidationFailedMessage)
 			return
 		}
 
 		err = ctx.Providers.SessionProvider.RegenerateSession(ctx.RequestCtx)
 
 		if err != nil {
-			ctx.Error(fmt.Errorf("Unable to regenerate session for user %s: %s", userSession.Username, err), authenticationFailedMessage)
+			// TODO: Shouldn't this be mfaValidationFailedMessage like the rest?
```
Comment (clems4ever) [inline internal/handlers/handler_sign_totp.go:42]: yes, you're right.

File: internal/handlers/handler_sign_u2f_step1.go [hunk 3]
```diff
@@ -13,12 +13,14 @@ import (
 
 // SecondFactorU2FSignGet handler for initiating a signing request.
 func SecondFactorU2FSignGet(ctx *middlewares.AutheliaCtx) {
+	// TODO: Should this be operationFailedMessage?
```
Comment (clems4ever) [inline internal/handlers/handler_sign_u2f_step1.go:16]: I would keep it because we don't want the public to know whether X-Forward-... is set or not in the backend...

Comment (clems4ever) [reply internal/handlers/handler_sign_u2f_step1.go:16]: I mean changing it would allow information disclosure for an attacker.

File: internal/handlers/handler_sign_u2f_step1.go [hunk 4]
```diff
@@ -13,12 +13,14 @@ import (
...
 	if ctx.XForwardedProto() == nil {
 		ctx.Error(errMissingXForwardedProto, operationFailedMessage)
 		return
 	}
 
 	if ctx.XForwardedHost() == nil {
+		// TODO: Should this be operationFailedMessage?
```
Comment (clems4ever) [inline internal/handlers/handler_sign_u2f_step1.go:23]: Same response as above.

File: internal/handlers/handler_sign_u2f_step2.go [hunk 5]
```diff
@@ -43,15 +43,16 @@ func SecondFactorU2FSignPost(u2fVerifier U2FVerifier) middlewares.RequestHandler
 		err = ctx.Providers.SessionProvider.RegenerateSession(ctx.RequestCtx)
 
 		if err != nil {
-			ctx.Error(fmt.Errorf("Unable to regenerate session for user %s: %s", userSession.Username, err), authenticationFailedMessage)
+			// TODO: Shouldn't this be mfaValidationFailedMessage like the rest?
```
Comment (clems4ever) [inline internal/handlers/handler_sign_u2f_step2.go:46]: you're right.

File: internal/handlers/handler_firstfactor.go [hunk 6]
```diff
@@ -36,15 +38,14 @@ func FirstFactorPost(ctx *middlewares.AutheliaCtx) {
...
-		ctx.Error(fmt.Errorf("Error while checking password for user %s: %s", bodyJSON.Username, err.Error()), authenticationFailedMessage)
+		handleErrorResponse(ctx, fmt.Errorf("Error while checking password for user %s: %s", bodyJSON.Username, err.Error()), authenticationFailedMessage)
 		return
 	}
 
 	if !userPasswordOk {
 		ctx.Logger.Debugf("Mark authentication attempt made by user %s", bodyJSON.Username)
 		ctx.Providers.Regulator.Mark(bodyJSON.Username, false) //nolint:errcheck // TODO: Legacy code, consider refactoring time permitting.
-
+		ctx.SetStatusCode(fasthttp.StatusUnauthorized)
```
Comment (clems4ever) [inline internal/handlers/handler_firstfactor.go:48]: you should also use `handleErrorResponse` here otherwise there is an easy way to know that branch has been reached by a hacker. I did it wrong at the beginning, we don't want to differentiate the message.

File: internal/handlers/handler_sign_u2f_step1.go (hunk 3 above)
Comment (james-d-elliott) [reply internal/handlers/handler_sign_u2f_step1.go:16]: @clems4ever I mean, in master we have it set to operationFailedMessage instead of mfaValidationFailedMessage.
