### PR TITLE
fix(authentication): discovery check too strict

### LINKED ISSUE #10840: v4.39.15 broken my Authelia service with LDAP Authentication
### Version

v4.39.15

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

3.6.2

### Description

My Authelia container was just automatically updated via Watchtower to version 4.39.15, and since then it won't start.

See the logs below.

My LDAP is a native Synology service hosted on my NAS, which is not the one running my containers.

I reverted to version 4.39.14, and everything is working perfectly again.

I checked the changelog and didn't find any configuration changes required.

What should I do?

### Reproduction

Same environment ?

### Expectations

_No response_

### Configuration (Authelia)

```yaml

```

### Build Information

```shell
Last Tag: v4.39.15
State: tagged clean
Branch: v4.39.15
Commit: b1d9a4905a7b35c3c283ee3aa08b6e5d862669c4
Build Number: 50508
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sat, 29 Nov 2025 23:08:48 +1100
Development: false
Extra: 

Go:
    Version: go1.25.3 X:nosynchashtriemap
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
time="2025-11-29T15:25:30+01:00" level=info msg="Authelia v4.39.15 is starting"
 time="2025-11-29T15:25:30+01:00" level=info msg="Log severity set to info"
 time="2025-11-29T15:25:30+01:00" level=info msg="Storage schema is being checked for updates"
 time="2025-11-29T15:25:30+01:00" level=info msg="Storage schema is already up to date"
 time="2025-11-29T15:25:30+01:00" level=error msg="Error occurred running a startup check" error="error occurred getting features from server: error occurred during RootDSE search: LDAP Result Code 53 \"Unwilling To Perform\": authentication required" provider=user
 time="2025-11-29T15:25:30+01:00" level=fatal msg="One or more providers had fatal failures performing startup checks, for more details check the error level logs" providers="[user]" stack="github.com/authelia/authelia/v4/internal/commands/root.go:93 (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.10.1/command.go:1015               (*Command).execute\ngithub.com/spf13/cobra@v1.10.1/command.go:1148               (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.10.1/command.go:1071               (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10      main\ninternal/runtime/atomic/types.go:194                         (*Uint32).Load\nruntime/asm_amd64.s:1693
```

### Logs (Proxy / Application)

```shell

```

### Documentation

_No response_

### Generative AI

No

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [ ] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [ ] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation

### PR DESCRIPTION
**Pull request by james-d-elliott**
This fixes an issue where discovery failure causes Authelia not to start. While the servers that work in this way are not officially supported it's reasonable to offer a best effort support to these severs.

Fixes #10840

### CODE REVIEW

File: internal/authentication/ldap_util.go [hunk 1]
```diff
@@ -33,51 +34,118 @@ func ldapGetFeatureSupportFromClient(client LDAPBaseClient) (features LDAPSuppor
...
-					features.Extensions.WhoAmI = true
-				}
-			}
+			ldapGetExtensionDiscoveryFromLDAPEntry(attr, &discovery.Extensions)
+		case ldapSupportedSASLMechanismsAttribute:
+			discovery.SASLMechanisms = attr.Values
+		case ldapSupportedFeaturesAttribute:
+			discovery.Features.OIDs = attr.Values
+		case ldapVendorNameAttribute:
+			discovery.Vendor.Name = strings.Join(attr.Values, " ")
```
Comment (autheliabot) [inline internal/authentication/ldap_util.go]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>undefined: strings

File: internal/authentication/ldap_util.go [hunk 2]
```diff
@@ -33,51 +34,118 @@ func ldapGetFeatureSupportFromClient(client LDAPBaseClient) (features LDAPSuppor
...
+		case ldapVendorVersionAttribute:
+			discovery.Vendor.Version = strings.Join(attr.Values, " ")
```
Comment (autheliabot) [inline internal/authentication/ldap_util.go]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>undefined: strings)) (typecheck)

File: internal/authentication/ldap_util.go (hunk 1 above)
Comment (autheliabot) [inline internal/authentication/ldap_util.go]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>undefined: strings

File: internal/authentication/ldap_util.go (hunk 2 above)
Comment (autheliabot) [inline internal/authentication/ldap_util.go]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>undefined: strings) (typecheck)

**Comment by Crowley723** [comment]
Are we thinking of doing this in a patch release?

File: docs/content/reference/integrations/ldap-integrations.md [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+that Authelia has every opportunity to automatically step-up the security of the authenticated bind. In addition it's
+important to ensure that the LDAP server supports LDAPv3.
+
+The two most critical elements for pre-bind discovery is the ability to perform StarTLS and the supported SASL
+mechanisms which both assist in preventing the password from being intercepted by a malicious actor.
+
+The LDAP server can either be setup to allow all users to anonymously perform the RootDSE search, or as per our current
+recommendation if the LDAP server supports it they can just allow the Authelia IP to anonymously perform the RootDSE
+search. This recommendation is purely precautionary based on certain LDAP servers discouraging all anonymous searches
+for unqualified security reasons as it pertains to the RootDSE which is specifically intened for the reason Authelia
```
Comment (nightah) [inline docs/content/reference/integrations/ldap-integrations.md]:
```suggestion
for unqualified security reasons as it pertains to the RootDSE, which is specifically intended for the reason Authelia
```

File: internal/authentication/ldap_user_provider_lifecycle.go [hunk 4]
```diff
@@ -29,34 +30,54 @@ func (p *LDAPUserProvider) StartupCheck() (err error) {
...
+	if discovery.Vendor.Name == ldapVendorNameMicrosoftCorporation {
+		p.log.Debugf("LDAP Discovery. LDAP Version: %s; Controls: %s; Extensions: %s; Features: %s; SASL Mechanisms: %s; Vendor Name: %s; Domain Functionality Level: %d, Forest Functionality Level: %d", version, controls, extensions, features, saslMechanisms, discovery.Vendor.Name, discovery.Vendor.DomainFunctionalLevel, discovery.Vendor.ForestFunctionalLevel)
+	} else {
+		p.log.Debugf("LDAP Discovery. LDAP Version: %s; Controls: %s; Extensions: %s; Features: %s; SASL Mechanisms: %s; Vendor Name: %s; Vendor Version; %s", version, controls, extensions, features, saslMechanisms, discovery.Vendor.Name, discovery.Vendor.Version)
 	}
 
-	p.log.Debugf("LDAP Supported OIDs. Control Types: %s. Extensions: %s", controlTypes, extensions)
+	if discovery.Successful {
+		if discovery.LDAPVersion == nil {
+			p.log.Warn("The configured LDAP server does not advertise the version of LDAP it supports or does not advertise the version it supports correctly. This server is unsupported.")
```
Comment (nightah) [inline internal/authentication/ldap_user_provider_lifecycle.go]:
```suggestion
			p.log.Warn("The configured LDAP server does not advertise the version of LDAP it supports or does not advertise the version it supports correctly. This server is not supported.")
```

File: internal/authentication/types.go [hunk 5]
```diff
@@ -234,29 +236,91 @@ type ldapUserProfileExtended struct {
 	*ldapUserProfile
 }
 
-// LDAPSupportedFeatures represents features which a server may support which are implemented in code.
-type LDAPSupportedFeatures struct {
-	Extensions   LDAPSupportedExtensions
-	ControlTypes LDAPSupportedControlTypes
+// LDAPDiscovery represents carious information about a server, such as LDAP Version, Features, Extensions, Controls.
```
Comment (nightah) [inline internal/authentication/types.go]:
```suggestion
// LDAPDiscovery represents various information about a server, such as LDAP Version, Features, Extensions, Controls.
```

File: internal/configuration/const.go [hunk 6]
```diff
@@ -54,8 +54,9 @@ const (
 	errFmtMultiKeyMappingExists      = "error occurred performing deprecation mapping for keys %s to new key %s: the new key already exists with value '%s' but the deprecated keys and the new key can't both be configured"
 	errFmtMultiKeyMappingPortConvert = "error occurred performing deprecation mapping for keys %s to new key %s: %w"
 
-	errFmtAutoMapKey         = "configuration key '%s' is deprecated in %s and has been replaced by '%s': " + errFmtSuffixAutoRemappedKey
-	errFmtAutoMapKeyExisting = "configuration key '%s' is deprecated in %s and has been replaced by '%s': this has not been automatically mapped for you because the replacement key also exists and you will need to adjust your configuration to remove this message"
+	errFmtAutoMapKey           = "configuration key '%s' is deprecated in %s and has been replaced by '%s': " + errFmtSuffixAutoRemappedKey
+	errFmtNoAutoMapKeyNoNewKey = "configuration key '%s' is deprecated in %s and has been removed': you are not required to make any configuration changes right now but you may be required to in %s"
```
Comment (nightah) [inline internal/configuration/const.go]:
```suggestion
	errFmtNoAutoMapKeyNoNewKey = "configuration key '%s' is deprecated in %s and has been removed: you are not required to make any configuration changes right now but you may be required to in %s"
```

File: internal/configuration/provider_test.go [hunk 7]
```diff
@@ -93,6 +93,25 @@ func TestShouldHaveNotifier(t *testing.T) {
...
+	testSetEnv(t, "AUTHENTICATION_BACKEND_LDAP_PASSWORD", "abc")
+
+	val := schema.NewStructValidator()
+	keys, config, err := Load(val, NewDefaultSources([]string{"./test_resources/config_no_automap.yml"}, DefaultEnvPrefix, DefaultEnvDelimiter)...)
+
+	assert.NoError(t, err)
+	assert.Len(t, val.Errors(), 0)
+	require.Len(t, val.Warnings(), 1)
+
+	assert.EqualError(t, val.Warnings()[0], "configuration key 'authentication_backend.ldap.permit_feature_detection_failure' is deprecated in 4.39.16 and has been removed': you are not required to make any configuration changes right now but you may be required to in 5.0.0")
```
Comment (nightah) [inline internal/configuration/provider_test.go]:
```suggestion
	assert.EqualError(t, val.Warnings()[0], "configuration key 'authentication_backend.ldap.permit_feature_detection_failure' is deprecated in 4.39.16 and has been removed: you are not required to make any configuration changes right now but you may be required to in 5.0.0")
```

**Review by nightah — DISMISSED** [review]
LGTM.

File: docs/content/reference/integrations/ldap-integrations.md [hunk 8]
```diff
@@ -0,0 +1,57 @@
...
+
+This page details the elements required for LDAP integrations to be considered supported.
+
+## Anonymous Discovery via the RootDSE Search
+
+LDAP servers must permit the query of the RootDSE object by Authelia prior to authentication. This is required to ensure
+that Authelia has every opportunity to automatically step-up the security of the authenticated bind. In addition it's
+important to ensure that the LDAP server supports LDAPv3.
+
+The two most critical elements for pre-bind discovery is the ability to perform StarTLS and the supported SASL
```
Comment (Crowley723) [inline docs/content/reference/integrations/ldap-integrations.md]:
```suggestion
The two most critical elements for pre-bind discovery is the ability to perform StartTLS and the supported SASL
```

Comment (nightah) [reply docs/content/reference/integrations/ldap-integrations.md]: Good catch.

**Review by Crowley723 — APPROVED** [review]
👍
