### PR TITLE
fix(storage): schema inconsistency

### LINKED ISSUE #4245: mysql: error: storage error loading authelia due to schema collation change
### Version

v4.37.0

### Deployment Method

Docker

### Reverse Proxy

SWAG

### Reverse Proxy Version

_No response_

### Description

Trying to start Authelia errors out, and naturally none of the containers I protect with Authelia are usable/accessible.

### Reproduction

All I did was pull the latest Authelia image.

### Expectations

_No response_

### Logs

```shell
From the log:


time="2022-10-23T02:16:06-05:00" level=warning msg="Configuration: configuration key 'server.read_buffer_size' is deprecated in 4.36.0 and has been replaced by 'server.buffers.read': this has been automatically mapped for you but you will need to adjust your configuration to remove this message"
time="2022-10-23T02:16:06-05:00" level=warning msg="Configuration: configuration key 'server.write_buffer_size' is deprecated in 4.36.0 and has been replaced by 'server.buffers.write': this has been automatically mapped for you but you will need to adjust your configuration to remove this message"
time="2022-10-23T02:16:06-05:00" level=warning msg="Configuration: configuration key 'authentication_backend.disable_reset_password' is deprecated in 4.36.0 and has been replaced by 'authentication_backend.password_reset.disable': this has been automatically mapped for you but you will need to adjust your configuration to remove this message"
time="2022-10-23T02:16:06-05:00" level=info msg="Authelia v4.37.0 is starting"
time="2022-10-23T02:16:06-05:00" level=info msg="Log severity set to debug"
{"level":"debug","msg":"Registering client [oc]-portainer with policy two_factor (2)","time":"2022-10-23T02:16:06-05:00"}
{"level":"info","msg":"Storage schema is being checked for updates","time":"2022-10-23T02:16:06-05:00"}
{"level":"info","msg":"Storage schema migration from 5 to 6 is being attempted","time":"2022-10-23T02:16:06-05:00"}
{"level":"error","msg":"Failure running the storage provider startup check: error during schema migrate: error applying migration version 6 to version 5 for rollback: schema migration 6 (ConsentPreConfiguration) failed: Error 1051: Unknown table 'authelia.oauth2_authorization_code_session'. rollback caused by: schema migration 6 (ConsentPreConfiguration) failed: Error 3780: Referencing column 'subject' and referenced column 'identifier' in foreign key constraint 'oauth2_consent_preconfiguration_subjct_fkey' are incompatible.","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":277,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.0/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.0/command.go","Line":1040,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.0/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-10-23T02:16:06-05:00"}
{"level":"debug","msg":"Notifier SMTP client attempting connection to smtp.gmail.com:465","time":"2022-10-23T02:16:06-05:00"}
{"level":"debug","msg":"Notifier SMTP client using submissions port 465. Make sure the mail server you are connecting to is configured for submissions and not SMTPS.","time":"2022-10-23T02:16:06-05:00"}
{"level":"debug","msg":"Notifier SMTP client connected successfully","time":"2022-10-23T02:16:06-05:00"}
{"level":"debug","msg":"Notifier SMTP connection is already encrypted, skipping STARTTLS","time":"2022-10-23T02:16:06-05:00"}
{"level":"debug","msg":"Notifier SMTP server supports authentication with the following mechanisms: LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH","time":"2022-10-23T02:16:06-05:00"}
{"level":"debug","msg":"Notifier SMTP client attempting AUTH PLAIN with server","time":"2022-10-23T02:16:06-05:00"}
{"level":"debug","msg":"Notifier SMTP client authenticated successfully with the server","time":"2022-10-23T02:16:06-05:00"}
{"level":"fatal","msg":"The following providers had fatal failures during startup: storage","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":305,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.0/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.0/command.go","Line":1040,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.0/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-10-23T02:16:07-05:00"}
```
```


### Configuration

_No response_

### Documentation

_No response_

### LINKED ISSUE #4336: Storage - Authelia not forcing to using InnoDB engine for new tables
### Version

v4.37.2

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

2.9.4

### Description

When using MySQL as storage for Authelia, I had the following settings in `my.cnf`

```sh
[mysqld]
default-storage-engine = MyISAM
...
```

A fresh installation of Authelia constantly crash, because all tables are created with MyISAM engine
```sh
MariaDB [(none)]> SELECT TABLE_NAME, ENGINE FROM information_schema.TABLES WHERE  TABLE_SCHEMA = 'authelia';
+-------------------------------------+--------+
| TABLE_NAME                          | ENGINE |
+-------------------------------------+--------+
| authentication_logs                 | MyISAM |
| duo_devices                         | MyISAM |
| encryption                          | MyISAM |
| identity_verification               | MyISAM |
| migrations                          | MyISAM |
| totp_configurations                 | MyISAM |
| u2f_devices                         | MyISAM |
| user_preferences                    | MyISAM |
| _bkp_DOWN_V0002_webauthn_devices    | MyISAM |
| _bkp_DOWN_V0002_totp_configurations | MyISAM |
| _bkp_UP_V0002_u2f_devices           | MyISAM |
| _bkp_UP_V0002_totp_configurations   | MyISAM |
+-------------------------------------+--------+
12 rows in set (0.001 sec)
```

Creating table with the specific engine can be achieved by using  - [link to docs](https://dev.mysql.com/doc/refman/5.7/en/using-innodb-tables.html)
```sh
CREATE TABLE t1 (a INT, b CHAR (20), PRIMARY KEY (a)) ENGINE=InnoDB;
```

Of course after changing `default-storage-engine = InnoDB` in `my.cnf` solve the problem and the fresh installation of Authelia works perfect.
```sh
MariaDB [(none)]> SELECT TABLE_NAME, ENGINE FROM information_schema.TABLES WHERE  TABLE_SCHEMA = 'authelia';
+-----------------------------------+--------+
| TABLE_NAME                        | ENGINE |
+-----------------------------------+--------+
| identity_verification             | InnoDB |
| user_preferences                  | InnoDB |
| _bkp_UP_V0002_u2f_devices         | InnoDB |
| totp_configurations               | InnoDB |
| oauth2_consent_session            | InnoDB |
| webauthn_devices                  | InnoDB |
| authentication_logs               | InnoDB |
| duo_devices                       | InnoDB |
| oauth2_pkce_request_session       | InnoDB |
| oauth2_authorization_code_session | InnoDB |
| oauth2_consent_preconfiguration   | InnoDB |
| oauth2_refresh_token_session      | InnoDB |
| _bkp_UP_V0002_totp_configurations | InnoDB |
| migrations                        | InnoDB |
| oauth2_openid_connect_session     | InnoDB |
| oauth2_blacklisted_jti            | InnoDB |
| encryption                        | InnoDB |
| user_opaque_identifier            | InnoDB |
| oauth2_access_token_session       | InnoDB |
+-----------------------------------+--------+
19 rows in set (0.001 sec)

```

### Reproduction

1. Change to `MyISAM` as the default Engine for new MySQL tables
```sh
[mysqld]
default-storage-engine = MyISAM
...
```

2. Add Storage configuration to `configuration.yml`
```yaml
storage:
  encryption_key:  my_secure_secret
  mysql:
    host: localhost
    port: 3306
    database: authelia
    username: authelia
    password: my_pass
    timeout: 5s
```
3. Run a new Authelia instance 
```yaml
version: "3.8"
services:
  authelia:
    image: authelia/authelia:4.37.2
    container_name: authelia
    expose:
      - 9091
    environment:
      - "TZ=Europe/Warsaw"
      - "PUID=1000"
      - "PGID=100"
    restart: unless-stopped
```

### Expectations

Authelia uses the proper MySQL Engine for tables, 

### Logs

```shell
time="2022-11-07T00:29:38+01:00" level=info msg="Authelia v4.37.2 is starting"
time="2022-11-07T00:29:38+01:00" level=info msg="Log severity set to debug"
time="2022-11-07T00:29:38+01:00" level=info msg="Storage schema is being checked for updates"
time="2022-11-07T00:29:38+01:00" level=info msg="Storage schema migration from 1 to 6 is being attempted"
time="2022-11-07T00:29:38+01:00" level=error msg="Failure running the storage provider startup check: error during schema migrate: error applying migration version 2 to version 1 for rollback: schema migration 2 (Webauthn) failed: Error 1050: Table '_bkp_DOWN_V0002_totp_configurations' already exists. rollback caused by: schema migration 2 (Webauthn) failed: Error 1050: Table '_bkp_UP_V0002_totp_configurations' already exists" stack="github.com/authelia/authelia/v4/internal/commands/root.go:281 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun\ngithub.com/spf13/cobra@v1.6.1/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.1/command.go:1044                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.1/command.go:968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1594                                      goexit"
time="2022-11-07T00:29:38+01:00" level=fatal msg="The following providers had fatal failures during startup: storage" stack="github.com/authelia/authelia/v4/internal/commands/root.go:309 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun\ngithub.com/spf13/cobra@v1.6.1/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.1/command.go:1044                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.1/command.go:968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1594                                      goexit"
```

### Configuration

_No response_

### Documentation

https://dev.mysql.com/doc/refman/5.7/en/using-innodb-tables.html

### PR DESCRIPTION
**Pull request by james-d-elliott**
This makes overall improvements to the schema migrations to mostly account for issues introduced by deprecated configurations that are no longer supported by the MySQL/MariaDB developers. It is not expressly a fix it is a workaround. However this also fixes some other misc inconsistencies in the database. It also more clearly defines the environment supported by Authelia.

Fixes #4245, Fixes #4336

### CODE REVIEW

**Comment by james-d-elliott** [comment]
1. Read all instructions in this post before starting anything.
2. Make a backup of the SQL database including both the schema and the database rows. This will have a high chance of breaking your database.
3. All data added to the database after the test should be considered lost.
4. The docker image name is `authelia\authelia:fix-sql-inconsistencies`.
5. Stop the container after you've verified it works. Then restore your SQL Backup.

@YouveGotMeowxy @nearcatch

**Comment by YouveGotMeowxy** [comment]
I'm sorry, I can't do any testing at the moment; I got hit with the latest Docker Desktop bug, had to uninstall/reinstall DD, which nuked all of my docker data, and I'm having issues getting everything back up. :/

**Comment by james-d-elliott** [comment]
> I'm sorry, I can't do any testing at the moment; I got hit with the latest Docker Desktop bug, had to uninstall/reinstall DD, which nuked all of my docker data, and I'm having issues getting everything back up. :/

No stress thanks for the reply.

**Comment by YouveGotMeowxy** [comment]
If I'm able to get things up while you're still needing the test, I'll be sure to do it.

File: cmd/authelia-gen/cmd_docs_cli.go [hunk 1]
```diff
@@ -98,10 +98,17 @@
...
+	var weight int
 
-	if name == "authelia" {
-		weight = 320
+	switch name {
+	case "authelia":
+		weight = 900
+	case "authelia-gen":
+		weight = 910
+	case "authelia-scripts":
```
Comment (autheliabot) [inline cmd/authelia-gen/cmd_docs_cli.go:108]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>string `authelia-scripts` has 2 occurrences, make it a constant (goconst)

File: cmd/authelia-gen/cmd_docs_cli.go [hunk 2]
```diff
@@ -98,10 +98,17 @@
 		return err
 	}
 
-	weight := 900
+	var weight int
 
-	if name == "authelia" {
-		weight = 320
+	switch name {
+	case "authelia":
```
Comment (autheliabot) [inline cmd/authelia-gen/cmd_docs_cli.go:104]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>string `authelia` has 2 occurrences, make it a constant (goconst)

File: cmd/authelia-gen/cmd_docs_cli.go [hunk 3]
```diff
@@ -98,10 +98,17 @@
...
+		weight = 900
+	case "authelia-gen":
```
Comment (autheliabot) [inline cmd/authelia-gen/cmd_docs_cli.go:106]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>string `authelia-gen` has 2 occurrences, but such constant `cmdUseRoot` already exists (goconst)
