### PR TITLE
fix(web): ui stuck state enrolling 2fa

### LINKED ISSUE #10859: enrolling 2FA to unknown email recipient result in 403 and UI being stuck
### Version

v4.39.13

### Deployment Method

Kubernetes

### Reverse Proxy

Traefik

### Reverse Proxy Version

3.5.3

### Description

I just created an LDAP account and tried to log in with it, requiring to enroll 2FA, but the UI is stuck on the ADD button loading.

Image

### Reproduction

The HTTP response to /api/user/session/elevation is 403, {"status":"KO","message":"Operation failed."}

And it's normal because the mail server, in my case, have no account for this email (it's not plugged to the LDAP).
`Recipient address rejected: User unknown in virtual mailbox table;`

But it's not normal that the UI stay stuck not giving any error message

### Expectations

Having an error message, with ideally the reason.

### Configuration (Authelia)

```yaml

```

### Build Information

```shell
Last Tag: v4.39.13
State: tagged clean
Branch: v4.39.13
Commit: 5a6e840e6f3f6b171ee05ce29e1c7cc2f3787ea4
Build Number: 49484
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sun, 12 Oct 2025 16:41:01 +1100
Development: false
Extra:

Go:
    Version: go1.25.1 X:nosynchashtriemap
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
authelia-6649b5447-tntn8 authelia time="2025-12-02T12:51:21+01:00" level=error msg="Error occurred creating user session elevation One-Time Code challenge for user 'lain': error occurred sending the user the notification" error="notifier: smtp: failed to send message: sending SMTP RCPT TO command: 550 5.1.1 <lain@XXX.XXX>: Recipient address rejected: User unknown in virtual mailbox table, affected recipient(s): <XXX@XXX.XXX>, affected message ID: <XXX@XXX.XXX>" method=POST path=/api/user/session/elevation remote_ip=10.42.0.106
```

### Logs (Proxy / Application)

```shell

```

### Documentation

_No response_

### Generative AI

No

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation

### PR DESCRIPTION
**Pull request by Br1an67**
Fixes #10859

## Summary

Fixes #10859: enrolling 2FA to unknown email recipient result in 403 and UI being stuck

### CODE REVIEW

File: internal/handlers/handler_session_elevation.go [hunk 1]
```diff
@@ -196,6 +196,11 @@ func UserSessionElevationPOST(ctx *middlewares.AutheliaCtx) {
 	if err = ctx.Providers.Notifier.Send(ctx, identity.Address(), data.Title, ctx.Providers.Templates.GetIdentityVerificationOTCEmailTemplate(), data); err != nil {
 		ctx.Logger.WithError(err).Errorf("Error occurred creating user session elevation One-Time Code challenge for user '%s': error occurred sending the user the notification", userSession.Username)
 
+		// Revoke the one-time code since the notification was not sent.
+		if errRevoke := ctx.Providers.StorageProvider.RevokeOneTimeCode(ctx, otp.PublicID, model.NewIP(ctx.RemoteIP())); errRevoke != nil {
+			ctx.Logger.WithError(errRevoke).Errorf("Error occurred revoking user session elevation One-Time Code challenge for user '%s': error occurred revoking the challenge from the storage backend", userSession.Username)
+		}
```
Comment (james-d-elliott) [inline internal/handlers/handler_session_elevation.go]:
```suggestion
```

The bug is with the UI, and an error sending does not necessarily mean it was not sent. The codes are secure and revocation should only be performed by an explicit action.

File: internal/handlers/handler_session_elevation_test.go [hunk 2]
```diff
@@ -420,6 +420,7 @@ func TestUserSessionElevationPOST(t *testing.T) {
 						OneTimeCode:        "ABC123ABC1",
 					}).
 						Return(fmt.Errorf("rejected")),
+						mock.StorageMock.EXPECT().RevokeOneTimeCode(mock.Ctx, uuid.Must(uuid.Parse("01020304-0506-4722-8910-111213141500")), model.NewIP(net.ParseIP("0.0.0.0"))).Return(nil),
```
Comment (james-d-elliott) [inline internal/handlers/handler_session_elevation_test.go]:
```suggestion
```

**Comment by nightah** [comment]
@all-contributors add @Br1an67 for code.
