### PR TITLE
fix(web): move reset password to after sign in

### LINKED ISSUE #2204: Change tab order for logon-form: Move "Forgot password" to *after* "Submit"
### Description
Currently when filling in Authelia's login form with just keyboard, it requires two tab-keypresses to go from the password field to the "Submit" button, because the "Forgot password" link gets focus first.

If the tab order is changed, this makes logging in slightly more intuitive.

### Use Case

_N/A_

### PR DESCRIPTION
**Pull request by james-d-elliott**
This is for a better user experience, specifically it makes it so when users tab through the elements in the login form they are selected in a logical order.

Fixes #2204

### CODE REVIEW

File: web/src/views/LoginPortal/FirstFactor/FirstFactorForm.tsx [hunk 1]
```diff
@@ -139,52 +139,36 @@
...
                     <Grid
                         item
                         xs={12}
-                        className={
-                            props.rememberMe
-                                ? classnames(style.leftAlign, style.actionRow)
-                                : classnames(style.leftAlign, style.flexEnd, style.actionRow)
-                        }
+                        className={classnames(style.leftAlign, style.actionRow)}
                     >
```
Comment (autheliabot) [inline web/src/views/LoginPortal/FirstFactor/FirstFactorForm.tsx:147]: 🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Replace `⏎························item⏎························xs={12}⏎························className={classnames(style.leftAlign,·style.actionRow)}⏎····················` with `·item·xs={12}·className={classnames(style.leftAlign,·style.actionRow)}`
```suggestion
                    <Grid item xs={12} className={classnames(style.leftAlign, style.actionRow)}>
```

File: web/src/views/LoginPortal/FirstFactor/FirstFactorForm.tsx [hunk 2]
```diff
@@ -199,6 +183,23 @@
                         Sign in
                     </Button>
                 </Grid>
+                {props.resetPassword ? (
+                    <Grid
+                        item
+                        xs={12}
+                        className={classnames(style.rightAlign, style.actionRow, style.flexEnd)}
+                    >
```
Comment (autheliabot) [inline web/src/views/LoginPortal/FirstFactor/FirstFactorForm.tsx:191]: 🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Replace `⏎························item⏎························xs={12}⏎························className={classnames(style.rightAlign,·style.actionRow,·style.flexEnd)}⏎····················` with `·item·xs={12}·className={classnames(style.rightAlign,·style.actionRow,·style.flexEnd)}`
```suggestion
                    <Grid item xs={12} className={classnames(style.rightAlign, style.actionRow, style.flexEnd)}>
```

File: web/src/views/LoginPortal/FirstFactor/FirstFactorForm.tsx [hunk 3]
```diff
@@ -139,52 +139,36 @@
...
                     <Grid
                         item
                         xs={12}
-                        className={
-                            props.rememberMe
-                                ? classnames(style.leftAlign, style.actionRow)
-                                : classnames(style.leftAlign, style.flexEnd, style.actionRow)
-                        }
+                        className={classnames(style.actionRow)}
                     >
```
Comment (autheliabot) [inline web/src/views/LoginPortal/FirstFactor/FirstFactorForm.tsx:147]: 🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Replace `⏎························item⏎························xs={12}⏎························className={classnames(style.actionRow)}⏎····················` with `·item·xs={12}·className={classnames(style.actionRow)}`
```suggestion
                    <Grid item xs={12} className={classnames(style.actionRow)}>
```

File: web/src/views/LoginPortal/FirstFactor/FirstFactorForm.tsx [hunk 4]
```diff
@@ -199,6 +183,22 @@
                         Sign in
                     </Button>
                 </Grid>
+                {props.resetPassword ? (
+                    <Grid
+                        item
+                        xs={12}
+                        className={classnames(style.actionRow, style.flexEnd)}
+                    >
```
Comment (autheliabot) [inline web/src/views/LoginPortal/FirstFactor/FirstFactorForm.tsx:191]: 🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Replace `⏎························item⏎························xs={12}⏎························className={classnames(style.actionRow,·style.flexEnd)}⏎····················` with `·item·xs={12}·className={classnames(style.actionRow,·style.flexEnd)}`
```suggestion
                    <Grid item xs={12} className={classnames(style.actionRow, style.flexEnd)}>
```

**Comment by james-d-elliott** [comment]
@clems4ever 

image


What do you think of this layout?

**Comment by clems4ever** [comment]
I'm fine with that.

**Review by nightah — APPROVED** [review]
LGTM!
