### PR TITLE
fix(server): missing cache-control header

### LINKED ISSUE #3732: Can we enable cache for the javascript files?
### Description

I'm trying the authelia(docker version, which image is: authelia/authelia) and found that the javascript files are not cached even their size large than 1M bytes for some js file. In some network environments it might needs more time to wait until open the login page of authelia.

Please add the max-age for the authelia javascript files to accelarator the login speed. Thanks!

### PR DESCRIPTION
**Pull request by james-d-elliott**
This fixes a missing cache control header.

Fixes #3732

### CODE REVIEW

**Review by nightah — APPROVED** [review]
LGTM.

More of a WDYT, do we add a simple integration test to check the header is present?

File: internal/server/asset.go [hunk 1]
```diff
@@ -20,10 +27,121 @@
...
+
+		sum := sha256.New()
+
+		sum.Write(data)
+
+		etags[p] = []byte(fmt.Sprintf("%x", sum.Sum(nil)))
+
+		fmt.Printf("%s: %s\n", p, etags[p])
+	}
+
```
Comment (autheliabot) [inline internal/server/asset.go:66]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>unnecessary trailing newline (whitespace)

File: internal/server/asset.go [hunk 2]
```diff
@@ -20,10 +27,121 @@
...
+func newPublicHTMLEmbeddedHandler2() fasthttp.RequestHandler {
+	etags := map[string][]byte{}
+
+	getEmbedETags(assets, "public_html", etags)
+
+	fmt.Printf("final etags:\n")
+
+	for key, etag := range etags {
+		fmt.Printf("%s: %s\n", key, etag)
+
```
Comment (autheliabot) [inline internal/server/asset.go:78]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>unnecessary trailing newline (whitespace)

File: internal/server/asset.go [hunk 3]
```diff
@@ -20,10 +27,121 @@
...
+		sum := sha256.New()
+
+		sum.Write(data)
+
+		etags[p] = []byte(fmt.Sprintf("%x", sum.Sum(nil)))
+
+		fmt.Printf("%s: %s\n", p, etags[p])
+	}
+
+}
```
Comment (autheliabot) [inline internal/server/asset.go:67]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>block should not end with a whitespace (or comment) (wsl)

File: internal/server/asset.go [hunk 4]
```diff
@@ -20,10 +27,121 @@
...
+	etags := map[string][]byte{}
+
+	getEmbedETags(assets, "public_html", etags)
+
+	fmt.Printf("final etags:\n")
+
+	for key, etag := range etags {
+		fmt.Printf("%s: %s\n", key, etag)
+
+	}
```
Comment (autheliabot) [inline internal/server/asset.go:79]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>block should not end with a whitespace (or comment) (wsl)

File: internal/server/const.go [hunk 5]
```diff
@@ -42,6 +46,9 @@
 )
 
 const (
+	css = ".css"
```
Comment (autheliabot) [inline internal/server/const.go:49]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`css` is unused (deadcode)

File: internal/server/const.go [hunk 6]
```diff
@@ -42,6 +46,9 @@
...
+	js  = ".js"
```
Comment (autheliabot) [inline internal/server/const.go:50]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`js` is unused (deadcode)

File: internal/server/const.go [hunk 7]
```diff
@@ -50,6 +57,15 @@
 	schemeHTTPS = "https"
 )
 
+var (
+	headerETag         = []byte(fasthttp.HeaderETag)
+	headerIfNoneMatch  = []byte(fasthttp.HeaderIfNoneMatch)
+	headerCacheControl = []byte(fasthttp.HeaderCacheControl)
+
+	headerValueCacheControlReact         = []byte("public, max-age=31536000, immutable")
```
Comment (autheliabot) [inline internal/server/const.go:65]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`headerValueCacheControlReact` is unused (deadcode)

File: internal/server/asset.go [hunk 8]
```diff
@@ -1,17 +1,21 @@
 package server
 
 import (
+	"bytes"
+	"crypto/sha1"
```
Comment (autheliabot) [inline internal/server/asset.go:5]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>G505: Blocklisted import crypto/sha1: weak cryptographic primitive (gosec)

File: internal/server/asset.go [hunk 9]
```diff
@@ -72,18 +110,46 @@
...
+
+		p := filepath.Join(root, entry.Name())
+
+		var data []byte
+
+		if data, err = embedFS.ReadFile(p); err != nil {
+			continue
+		}
+
+		sum := sha1.New()
```
Comment (autheliabot) [inline internal/server/asset.go:138]: 🚫 **[golangci]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>G401: Use of weak cryptographic primitive (gosec)

**Review by nightah — APPROVED** [review]
LGTM.
