### PR TITLE
[FIX] Disable regulation when max_retries set to 0 (#584)

### LINKED ISSUE #584: Error disabling authentication regulation
From the template:

```yaml
# Configuration of the authentication regulation mechanism.
#
# This mechanism prevents attackers from brute forcing the first factor.
# It bans the user if too many attempts are done in a short period of
# time.
regulation:
  # The number of failed login attempts before user is banned.
  # Set it to 0 to disable regulation.
  max_retries: 3
```

However, changing `max_retries` to 0 results in an error:
```
panic: runtime error: index out of range [0] with length 0
goroutine 35 [running]:
github.com/authelia/authelia/internal/regulation.(*Regulator).Regulate(0x400026ef40, 0x400036c338, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/authelia/authelia@/internal/regulation/regulator.go:75 +0x3cc
github.com/authelia/authelia/internal/handlers.FirstFactorPost(0x400039e000)
        github.com/authelia/authelia@/internal/handlers/handler_firstfactor.go:25 +0x90
github.com/authelia/authelia/internal/middlewares.AutheliaMiddleware.func1.1(0x400037e000)
        github.com/authelia/authelia@/internal/middlewares/authelia_context.go:46 +0x114
github.com/fasthttp/router.(*Router).Handler(0x40003083c0, 0x400037e000)
        github.com/fasthttp/router@v0.5.2/router.go:326 +0xc48
github.com/authelia/authelia/internal/middlewares.LogRequestMiddleware.func1(0x400037e000)
        github.com/authelia/authelia@/internal/middlewares/log_request.go:14 +0xd4
github.com/valyala/fasthttp.(*Server).serveConn(0x4000328200, 0xf04380, 0x40002dc018, 0x0, 0x0)
        github.com/valyala/fasthttp@v1.6.0/server.go:2018 +0x4f8
github.com/valyala/fasthttp.(*workerPool).workerFunc(0x4000270aa0, 0x40002de060)
        github.com/valyala/fasthttp@v1.6.0/workerpool.go:223 +0x7c
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0x4000270aa0, 0x40002de060, 0xbc3f60, 0x40002de060)
        github.com/valyala/fasthttp@v1.6.0/workerpool.go:195 +0x30
created by github.com/valyala/fasthttp.(*workerPool).getCh
        github.com/valyala/fasthttp@v1.6.0/workerpool.go:194 +0x11c
```

### PR DESCRIPTION
**Pull request by james-d-elliott**
- Only set regulator to enabled if max_retries is not set to 0, default is false (zero value). See 
https://tour.golang.org/basics/12.
- Added test for the scenario.
- Fixes #584

I have PR's #588 and #589 open, and will rebase & force push which ever one is not merged first (and this is to be expected behaviour from me unless you have an alternate preference).

### CODE REVIEW

**Comment by james-d-elliott** [comment]
Looks like my test failed, going to figure out why.

**Comment by james-d-elliott** [comment]
Okay I cleared the error but I think at a sacrifice for the test actually functioning. 

I originally used the s.storageMock.EXPECT().LoadLatestAuthenticationLogs().Return() functionality of the others, but obviously due to the regulator never checking for the logs it failed. I'm not 100% sure how to do this properly, going to experiment with another branch for testing.

File: internal/regulation/regulator.go [hunk 1]
```diff
@@ -18,7 +18,10 @@ func NewRegulator(configuration *schema.RegulationConfiguration, provider storag
 		if configuration.FindTime > configuration.BanTime {
 			panic(fmt.Errorf("find_time cannot be greater than ban_time"))
 		}
-		regulator.enabled = true
+		// Set regulator enabled only if MaxRetries is not 0.
+		if configuration.MaxRetries != 0 {
```
Comment (clems4ever) [inline internal/regulation/regulator.go]: you can simply write `regulator.enabled = configuration.MaxRetries > 0`.

**Comment by clems4ever** [comment]
Thanks for the fix @james-d-elliott . Are you ok to merge the PR as it is right now? It seems your current test correctly covers the issue.

**Comment by james-d-elliott** [comment]
This is ready to merge. As per our conversation in Matrix, this now properly checks the enabled/disabled functionality. 

The following branch shows what occurs if we incorporate a change that would alter the functionality:

https://github.com/authelia/authelia/tree/unit-test/regulation

**Comment by nightah** [comment]
LGTM!
